import { INoteSummary } from '../models/note-summary.model';
import { INoteTranscript } from '../models/note-transcript.model';
import { env } from '../../config/env';

export function buildSummaryEmail(
  summary: INoteSummary,
  sessionId: string,
  meetingTitle: string,
  meetingDate: string,
  durationMinutes: number,
  participantNames: string[],
): string {
  const transcriptUrl = `${env.FRONTEND_URL}/meet/notes/${sessionId}`;

  const actionItemsHtml = summary.actionItems.length > 0
    ? `<h3 style="color: #1a1a2e; margin-top: 24px;">Action Items</h3>
       <ul style="padding-left: 20px;">
         ${summary.actionItems.map((item) => {
           let line = item.description;
           if (item.assignee) line += ` <strong>(${item.assignee})</strong>`;
           if (item.deadline) line += ` — by ${item.deadline}`;
           return `<li style="margin-bottom: 8px;">${line}</li>`;
         }).join('')}
       </ul>`
    : '';

  const decisionsHtml = summary.decisions.length > 0
    ? `<h3 style="color: #1a1a2e; margin-top: 24px;">Key Decisions</h3>
       <ul style="padding-left: 20px;">
         ${summary.decisions.map((d) => `<li style="margin-bottom: 6px;">${d}</li>`).join('')}
       </ul>`
    : '';

  const questionsHtml = summary.questions.length > 0
    ? `<h3 style="color: #1a1a2e; margin-top: 24px;">Open Questions</h3>
       <ul style="padding-left: 20px;">
         ${summary.questions.map((q) => `<li style="margin-bottom: 6px;">${q}</li>`).join('')}
       </ul>`
    : '';

  const topicsHtml = summary.keyTopics.length > 0
    ? `<div style="margin-top: 16px;">
         ${summary.keyTopics.map((t) =>
           `<span style="display: inline-block; background: #e8eaf6; color: #3949ab; padding: 4px 12px; border-radius: 16px; font-size: 13px; margin: 2px 4px;">${t}</span>`
         ).join('')}
       </div>`
    : '';

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body style="margin: 0; padding: 0; background: #f5f5f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;">
  <div style="max-width: 640px; margin: 0 auto; padding: 24px;">
    <div style="background: white; border-radius: 12px; padding: 32px; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">

      <div style="border-bottom: 1px solid #eee; padding-bottom: 16px; margin-bottom: 24px;">
        <h1 style="margin: 0; color: #1a1a2e; font-size: 22px;">${meetingTitle}</h1>
        <p style="margin: 8px 0 0; color: #666; font-size: 14px;">
          ${meetingDate} · ${durationMinutes} min · ${participantNames.length} participant${participantNames.length !== 1 ? 's' : ''}
        </p>
        <p style="margin: 4px 0 0; color: #888; font-size: 13px;">
          ${participantNames.join(', ')}
        </p>
      </div>

      ${topicsHtml}

      <h3 style="color: #1a1a2e; margin-top: 24px;">Summary</h3>
      <p style="color: #333; line-height: 1.6; font-size: 15px;">${summary.overview}</p>

      ${actionItemsHtml}
      ${decisionsHtml}
      ${questionsHtml}

      <div style="margin-top: 32px; text-align: center;">
        <a href="${transcriptUrl}" style="display: inline-block; background: #3949ab; color: white; padding: 12px 28px; border-radius: 8px; text-decoration: none; font-weight: 500; font-size: 15px;">
          View Full Transcript
        </a>
      </div>

      <p style="margin-top: 32px; color: #999; font-size: 12px; text-align: center; border-top: 1px solid #eee; padding-top: 16px;">
        This summary was generated by NetworkChains Note-Taker.
      </p>
    </div>
  </div>
</body>
</html>`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function formatTimestamp(seconds: number): string {
  const s = Math.floor(seconds);
  const hh = Math.floor(s / 3600);
  const mm = Math.floor((s % 3600) / 60);
  const ss = s % 60;
  const pad = (n: number) => String(n).padStart(2, '0');
  return hh > 0 ? `${hh}:${pad(mm)}:${pad(ss)}` : `${pad(mm)}:${pad(ss)}`;
}

/**
 * Fallback email used when summary generation failed (e.g. LLM rate
 * limited). Renders the raw transcript grouped by speaker so the meeting
 * notes still reach recipients — better than nothing.
 */
export function buildTranscriptFallbackEmail(
  transcript: INoteTranscript,
  sessionId: string,
  meetingTitle: string,
  meetingDate: string,
  durationMinutes: number,
  participantNames: string[],
): string {
  const transcriptUrl = `${env.FRONTEND_URL}/meet/notes/${sessionId}`;

  const segmentsHtml = (transcript.segments ?? [])
    .map((seg) => {
      const speaker = escapeHtml(seg.speakerName || seg.speaker || 'Unknown');
      const ts = formatTimestamp(seg.startTime);
      const text = escapeHtml(seg.text);
      return `<div style="margin-bottom: 14px;">
        <div style="color: #3949ab; font-weight: 600; font-size: 14px;">${speaker} <span style="color: #999; font-weight: 400; font-size: 12px;">· ${ts}</span></div>
        <div style="color: #333; line-height: 1.6; font-size: 15px; margin-top: 2px;">${text}</div>
      </div>`;
    })
    .join('');

  const transcriptBlock = segmentsHtml
    ? `<div style="max-height: 600px; overflow-y: auto; padding: 4px;">${segmentsHtml}</div>`
    : `<p style="color: #333; line-height: 1.6; font-size: 15px; white-space: pre-wrap;">${escapeHtml(transcript.fullText || '')}</p>`;

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body style="margin: 0; padding: 0; background: #f5f5f5; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;">
  <div style="max-width: 640px; margin: 0 auto; padding: 24px;">
    <div style="background: white; border-radius: 12px; padding: 32px; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">

      <div style="border-bottom: 1px solid #eee; padding-bottom: 16px; margin-bottom: 24px;">
        <h1 style="margin: 0; color: #1a1a2e; font-size: 22px;">${meetingTitle}</h1>
        <p style="margin: 8px 0 0; color: #666; font-size: 14px;">
          ${meetingDate} · ${durationMinutes} min · ${participantNames.length} participant${participantNames.length !== 1 ? 's' : ''}
        </p>
        <p style="margin: 4px 0 0; color: #888; font-size: 13px;">
          ${participantNames.join(', ')}
        </p>
      </div>

      <div style="background: #fff8e1; border: 1px solid #ffe082; color: #795548; padding: 12px 14px; border-radius: 8px; font-size: 13px; margin-bottom: 20px;">
        Summary generation was unavailable, so we're sending the full transcript instead.
      </div>

      <h3 style="color: #1a1a2e; margin-top: 8px;">Transcript</h3>
      ${transcriptBlock}

      <div style="margin-top: 32px; text-align: center;">
        <a href="${transcriptUrl}" style="display: inline-block; background: #3949ab; color: white; padding: 12px 28px; border-radius: 8px; text-decoration: none; font-weight: 500; font-size: 15px;">
          View Full Transcript
        </a>
      </div>

      <p style="margin-top: 32px; color: #999; font-size: 12px; text-align: center; border-top: 1px solid #eee; padding-top: 16px;">
        Sent by NetworkChains Note-Taker.
      </p>
    </div>
  </div>
</body>
</html>`;
}
