/**
 * Backup all BAT246 collections to JSON, write an MD restore guide, then wipe all data.
 * Run: npx ts-node src/bat246/scripts/backupAndWipeBat246.ts
 *
 * Output files (created in project root):
 *   bat246-backup-<timestamp>.json   — raw data for programmatic restore
 *   bat246-backup-<timestamp>.md     — human-readable summary + restore instructions
 */
import mongoose from "mongoose";
import dotenv from "dotenv";
import fs from "fs";
import path from "path";

dotenv.config();

// ── Import every model so Mongoose registers the schemas ──────────────────────
import { Bat246Board }       from "../models/bat246Board.model";
import { Bat246Player }      from "../models/bat246Player.model";
import { Bat246PlayerBoard } from "../models/bat246PlayerBoard.model";
import { Bat246Movement }    from "../models/bat246Movement.model";
import { Bat246Config }      from "../models/bat246Config.model";
import { Bat246Distributor } from "../models/bat246Distributor.model";
import { Bat246FreeEntry }   from "../models/bat246FreeEntry.model";
import { Bat246Recruitment } from "../models/bat246Recruitment.model";
import { Bat246SalesCredit } from "../models/bat246SalesCredit.model";
import { Bat246SnapBackLoan }from "../models/bat246SnapBackLoan.model";
import { Bat246TopTen }      from "../models/bat246TopTen.model";

const MONGO_URI = process.env.MONGODB_URI || "mongodb://localhost:27017/garage";

const COLLECTIONS = [
  { name: "bat246Boards",       model: Bat246Board },
  { name: "bat246Players",      model: Bat246Player },
  { name: "bat246PlayerBoards", model: Bat246PlayerBoard },
  { name: "bat246Movements",    model: Bat246Movement },
  { name: "bat246Config",       model: Bat246Config },
  { name: "bat246Distributors", model: Bat246Distributor },
  { name: "bat246FreeEntries",  model: Bat246FreeEntry },
  { name: "bat246Recruitments", model: Bat246Recruitment },
  { name: "bat246SalesCredits", model: Bat246SalesCredit },
  { name: "bat246SnapBackLoans",model: Bat246SnapBackLoan },
  { name: "bat246TopTen",       model: Bat246TopTen },
] as const;

async function run() {
  await mongoose.connect(MONGO_URI);
  console.log("Connected to MongoDB\n");

  // ── 1. Fetch all data ─────────────────────────────────────────────────────
  const backup: Record<string, any[]> = {};
  const counts: Record<string, number> = {};

  for (const col of COLLECTIONS) {
    const docs = await (col.model as any).find({}).lean();
    backup[col.name] = docs;
    counts[col.name] = docs.length;
    console.log(`  Fetched ${docs.length.toString().padStart(4)} docs from ${col.name}`);
  }

  const timestamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  // The folder that contains the repo, so the backup (live player data) lands
  // outside git. In the old split layout that was "../../../../.." from
  // src/bat246/scripts; server/ sits one level higher in the combined repo.
  const outDir = path.resolve(__dirname, "../../../..");
  const jsonFile = path.join(outDir, `bat246-backup-${timestamp}.json`);
  const mdFile   = path.join(outDir, `bat246-backup-${timestamp}.md`);

  // ── 2. Write JSON backup ──────────────────────────────────────────────────
  fs.writeFileSync(jsonFile, JSON.stringify(backup, null, 2), "utf8");
  console.log(`\nJSON backup saved → ${jsonFile}`);

  // ── 3. Write MD restore guide ─────────────────────────────────────────────
  const totalDocs = Object.values(counts).reduce((a, b) => a + b, 0);

  const boardSummary = (backup["bat246Boards"] as any[]).map((b: any) =>
    `| ${b.boardNumber ?? "—"} | ${b.trackingNumber ?? "—"} | ${b.status} | ${b.generation ?? 0} | ${(b.atBat ?? []).filter(Boolean).length}/8 AT BAT | ${b.dugout?.length ?? 0} dugout |`
  ).join("\n");

  const playerSummary = (backup["bat246Players"] as any[]).map((p: any) =>
    `| ${p.playerIdNo ?? "—"} | ${p.email ?? "—"} | ${p.nickname ?? "—"} | entries: ${p.minorLeague?.totalEntries ?? 0} |`
  ).join("\n");

  const md = `# BAT246 Full Backup — ${timestamp.replace("T", " ").replace(/-/g, (m, i) => i < 10 ? "-" : ":")}

> Generated by \`backupAndWipeBat246.ts\`. All data wiped after this file was created.

## Document Counts

| Collection | Count |
|---|---|
${Object.entries(counts).map(([k, v]) => `| ${k} | ${v} |`).join("\n")}
| **TOTAL** | **${totalDocs}** |

---

## Boards Summary

| Board# | Tracking | Status | Gen | AT BAT | Dugout |
|---|---|---|---|---|---|
${boardSummary || "_(none)_"}

---

## Players Summary

| PlayerID | Email | Nickname | Stats |
|---|---|---|---|
${playerSummary || "_(none)_"}

---

## How to Restore

The raw JSON backup is at: \`bat246-backup-${timestamp}.json\`

### Option A — Quick restore script

Create a file \`src/bat246/scripts/restoreBat246.ts\`:

\`\`\`typescript
import mongoose from "mongoose";
import dotenv from "dotenv";
import fs from "fs";
dotenv.config();

import { Bat246Board }        from "../models/bat246Board.model";
import { Bat246Player }       from "../models/bat246Player.model";
import { Bat246PlayerBoard }  from "../models/bat246PlayerBoard.model";
import { Bat246Movement }     from "../models/bat246Movement.model";
import { Bat246Config }       from "../models/bat246Config.model";
import { Bat246Distributor }  from "../models/bat246Distributor.model";
import { Bat246FreeEntry }    from "../models/bat246FreeEntry.model";
import { Bat246Recruitment }  from "../models/bat246Recruitment.model";
import { Bat246SalesCredit }  from "../models/bat246SalesCredit.model";
import { Bat246SnapBackLoan } from "../models/bat246SnapBackLoan.model";
import { Bat246TopTen }       from "../models/bat246TopTen.model";

const BACKUP_FILE = "bat246-backup-${timestamp}.json";
const MONGO_URI = process.env.MONGODB_URI || "mongodb://localhost:27017/garage";

const MODEL_MAP: Record<string, any> = {
  bat246Boards:       Bat246Board,
  bat246Players:      Bat246Player,
  bat246PlayerBoards: Bat246PlayerBoard,
  bat246Movements:    Bat246Movement,
  bat246Config:       Bat246Config,
  bat246Distributors: Bat246Distributor,
  bat246FreeEntries:  Bat246FreeEntry,
  bat246Recruitments: Bat246Recruitment,
  bat246SalesCredits: Bat246SalesCredit,
  bat246SnapBackLoans:Bat246SnapBackLoan,
  bat246TopTen:       Bat246TopTen,
};

async function restore() {
  await mongoose.connect(MONGO_URI);
  const data = JSON.parse(fs.readFileSync(BACKUP_FILE, "utf8"));
  for (const [colName, docs] of Object.entries(data) as [string, any[]][]) {
    if (!docs.length) continue;
    const M = MODEL_MAP[colName];
    await M.insertMany(docs, { ordered: false });
    console.log(\`Restored \${docs.length} docs into \${colName}\`);
  }
  await mongoose.disconnect();
  console.log("Restore complete.");
}

restore().catch(err => { console.error(err); process.exit(1); });
\`\`\`

Run: \`npx ts-node src/bat246/scripts/restoreBat246.ts\`

### Option B — mongorestore (if you have a mongodump backup separately)
\`mongorestore --uri="<MONGO_URI>" --db=garage --collection=bat246Boards dump/garage/bat246Boards.bson\`

---

_Backup created at ${new Date().toISOString()}_
`;

  fs.writeFileSync(mdFile, md, "utf8");
  console.log(`MD guide saved    → ${mdFile}\n`);

  // ── 4. Wipe all collections ───────────────────────────────────────────────
  console.log("Wiping all BAT246 collections...");
  for (const col of COLLECTIONS) {
    const result = await (col.model as any).deleteMany({});
    console.log(`  Deleted ${result.deletedCount.toString().padStart(4)} docs from ${col.name}`);
  }

  console.log("\nAll BAT246 data wiped. Backup files:");
  console.log(`  JSON: ${jsonFile}`);
  console.log(`  MD:   ${mdFile}`);

  await mongoose.disconnect();
  console.log("\nDone.");
}

run().catch(err => {
  console.error(err);
  process.exit(1);
});
