/** Shared typography for Import / Export UI */
export const ie = {
  pageTitle: "text-base font-semibold text-white",
  pageSubtitle: "text-sm font-normal text-white/50",
  tab: "text-sm font-medium",
  stepBadge: "text-xs font-semibold",
  stepLabel: "text-sm font-medium",
  sectionTitle: "text-sm font-semibold text-white",
  sectionDesc: "text-sm font-normal text-white/50",
  columnTitle: "text-xs font-medium uppercase tracking-wide",
  columnTitleIdle: "text-white/40",
  columnTitleActive: "text-brand",
  summaryLabel: "text-xs font-medium uppercase tracking-wide text-brand/70",
  summaryValue: "text-sm font-medium text-brand",
  cardLabel: "text-sm font-medium",
  cardLabelSelected: "text-brand",
  cardLabelIdle: "text-white",
  placeholder: "text-sm font-normal text-white/40",
  empty: "text-sm font-normal text-white/40",
  hint: "text-xs font-normal text-white/40",
  table: "text-sm",
  tableHead: "text-xs font-medium uppercase tracking-wide text-white/40",
  tableCell: "text-sm font-normal text-white/75",
  tableCellStrong: "text-sm font-medium text-white",
  tableCellMuted: "text-sm font-normal text-white/50",
  select:
    "w-full h-9 rounded-lg border border-white/10 bg-[#0a0a0d] px-2.5 text-sm font-normal text-white outline-none focus:outline-none focus:ring-0 focus:border-white/10",
  selectPlaceholder: "text-sm font-normal text-white/40",
  chip: "text-xs font-normal text-white/70",
  badge: "text-xs font-normal uppercase tracking-wide text-white/40",
  sectionDivider: "text-xs font-semibold uppercase tracking-wide text-brand/80",
  backBtn: "text-sm font-normal text-white/50 hover:text-white",
  ghostBtn: "text-sm font-normal text-white/70 hover:text-white",
  actionBtn: "text-sm font-medium",
} as const;
